package analysis

import (
	"fmt"
	"io"
	"strings"

	"github.com/umbralcalc/18xxdesigner/pkg/gamedata"
)

// WriteReport generates a Markdown balance report to w.
func WriteReport(w io.Writer, m BatchMetrics, cfg *gamedata.GameConfig, hexes []gamedata.HexDef) {
	p := func(format string, args ...any) { fmt.Fprintf(w, format+"\n", args...) }

	p("# 18xxdesigner Balance Report")
	p("")
	p("**Game:** %s", cfg.Title)
	p("**Players:** %d | **Simulations:** %d", m.NumPlayers, m.NumGames)
	p("")

	// Game length.
	p("## Game Length")
	p("")
	p("| Metric | Value |")
	p("|--------|-------|")
	p("| Mean | %.0f steps |", m.GameLengthMean)
	p("| Std Dev | %.0f |", m.GameLengthStdDev)
	p("| Min | %d |", m.GameLengthMin)
	p("| Max | %d |", m.GameLengthMax)
	p("")

	// Player balance.
	p("## Player Balance")
	p("")
	p("**Gini coefficient:** %.3f (0 = equal, 1 = monopoly)", m.GiniCoefficient)
	p("")
	p("| Player | Wins | Win%% | Mean Portfolio | Std Dev |")
	p("|--------|------|------|---------------|---------|")
	for i := 0; i < m.NumPlayers; i++ {
		winPct := float64(m.WinsByPlayer[i]) / float64(m.NumGames) * 100
		p("| P%d | %d | %.0f%% | %.0f | %.0f |",
			i, m.WinsByPlayer[i], winPct, m.PortfolioMean[i], m.PortfolioStdDev[i])
	}
	p("")
	p("**Comeback rate:** %.0f%% (games where first-mover did NOT win)",
		m.ComebackRate*100)
	p("")

	// Company statistics.
	p("## Company Statistics")
	p("")
	p("| Company | Float%% | Survival%% | Mean Revenue |")
	p("|---------|--------|-----------|-------------|")
	for i, c := range cfg.Companies {
		if i < len(m.CompanyFloatRate) {
			p("| %s | %.0f%% | %.0f%% | %.0f |",
				c.Sym,
				m.CompanyFloatRate[i]*100,
				m.CompanySurvivalRate[i]*100,
				m.CompanyMeanRevenue[i])
		}
	}
	p("")

	// Hex utilization.
	p("## Hex Utilization")
	p("")
	p("| Hex | Util%% |")
	p("|-----|-------|")
	for i, h := range hexes {
		if i < len(m.HexUtilization) && m.HexUtilization[i] > 0 {
			p("| %s | %.0f%% |", h.ID, m.HexUtilization[i]*100)
		}
	}
	p("")
	p("---")
	p("*Generated by 18xxdesigner*")
}

// WriteComparisonReport generates a side-by-side comparison of two configs.
func WriteComparisonReport(w io.Writer, label1 string, m1 BatchMetrics, label2 string, m2 BatchMetrics, cfg *gamedata.GameConfig) {
	p := func(format string, args ...any) { fmt.Fprintf(w, format+"\n", args...) }

	p("# 18xxdesigner Comparison Report")
	p("")
	p("**Game:** %s", cfg.Title)
	p("**Comparing:** %s vs %s", label1, label2)
	p("**Simulations:** %d each", m1.NumGames)
	p("")

	// Game length comparison.
	p("## Game Length")
	p("")
	p("| Metric | %s | %s | Delta |", label1, label2)
	p("|--------|%s|%s|-------|", pad(len(label1)+2), pad(len(label2)+2))
	p("| Mean | %.0f | %.0f | %+.0f |", m1.GameLengthMean, m2.GameLengthMean,
		m2.GameLengthMean-m1.GameLengthMean)
	p("")

	// Gini comparison.
	p("## Player Balance")
	p("")
	p("| Metric | %s | %s | Delta |", label1, label2)
	p("|--------|%s|%s|-------|", pad(len(label1)+2), pad(len(label2)+2))
	p("| Gini | %.3f | %.3f | %+.3f |", m1.GiniCoefficient, m2.GiniCoefficient,
		m2.GiniCoefficient-m1.GiniCoefficient)
	p("| Comeback | %.0f%% | %.0f%% | %+.0f%% |",
		m1.ComebackRate*100, m2.ComebackRate*100,
		(m2.ComebackRate-m1.ComebackRate)*100)
	p("")

	// Company float rate comparison.
	p("## Company Float Rates")
	p("")
	p("| Company | %s | %s | Delta |", label1, label2)
	p("|---------|%s|%s|-------|", pad(len(label1)+2), pad(len(label2)+2))
	for i, c := range cfg.Companies {
		if i < len(m1.CompanyFloatRate) && i < len(m2.CompanyFloatRate) {
			p("| %s | %.0f%% | %.0f%% | %+.0f%% |",
				c.Sym,
				m1.CompanyFloatRate[i]*100,
				m2.CompanyFloatRate[i]*100,
				(m2.CompanyFloatRate[i]-m1.CompanyFloatRate[i])*100)
		}
	}
	p("")
	p("---")
	p("*Generated by 18xxdesigner*")
}

func pad(n int) string {
	return strings.Repeat("-", n)
}
